
### get current ticket
GET http://localhost:8000/api/ticket/1 HTTP/1.1
content-type: application/json

### Get all tickets
GET http://localhost:8001/api/teachers/ HTTP/1.1
content-type: application/json

GET http://localhost:8001/api/tickets/ HTTP/1.1
content-type: application/json

GET http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json




### Create a ticket
POST http://localhost:8000/api/ticket/create HTTP/1.1
content-type: application/json

{
    "submission_date": "2024-09-18",
    "customer_name": "Елена Бушмелева",
    "room_number": "№41",
    "problem_title": "Устранение технических неполадок",
    "problems": [
        { "pc_name": "ПК №4", "tasks": [ { "text": "Ремонт ПК" }, { "text": "Чистка ПК" }, { "text": "Установка ПО" } ], "description": "some description" }
    ]
}

### Remove some ticket
DELETE http://localhost:8000/api/ticket/3 HTTP/1.1
content-type: application/json