
### get current ticket
GET http://localhost:5000/api/ticket/1 HTTP/1.1
content-type: application/json

### Get all tickets
GET http://localhost:5000/api/ticket/all HTTP/1.1
content-type: application/json

### Create a ticket
POST http://localhost:5000/api/ticket/create HTTP/1.1
content-type: application/json

{
    "audience": 41,
    "tasks": [
        { "id": 1, "pc_num": "№4", "badges": [ { "id": 1, "title": "ПК не включается" } ] }
    ],
    "customer": "Елена Бушмелева"
}

### Remove some ticket
DELETE http://localhost:5000/api/ticket/3 HTTP/1.1
content-type: application/json