
### get current ticket
GET http://localhost:8001/api/tickets/ HTTP/1.1
content-type: application/json

{
    "role": "administrator",
    "user_id": 1
}

### Get all teachers
GET http://localhost:8001/api/teachers/ HTTP/1.1
content-type: application/json


###
GET http://localhost:8001/api/tickets/ HTTP/1.1
content-type: application/json

###
GET http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json




### Create a ticket
POST http://localhost:8001/api/ticket/create HTTP/1.1
content-type: application/json

{
    "submission_date": "2024-03-20",
    "customer_name": "Елена Бушмелева",
    "room_number": "101",
    "problem_title": "Internet Connection Issue",
    "state_id": 1,
    "teacher_id": 2,
    "tasks": [
        {
            "pc_name": "PC1",
            "works": [
                {
                    "task_description": "Check network cables"
                },
                {
                    "task_description": "Reboot the router"
                }
            ]
        },
        {
            "pc_name": "PC2",
            "works": [
                {
                    "task_description": "Check router settings"
                },
                {
                    "task_description": "Contact ISP"
                }
            ]
        }
    ]
}


############ Teachers #################
### Create a teacher
POST http://localhost:8001/api/teachers/ HTTP/1.1
content-type: application/json

{
    "teacher_name": "Ларионов Андрей",
    "department": "Информатика",
    "role": "administrator"
}

### get all teachers
GET http://localhost:8001/api/teachers/ HTTP/1.1
content-type: application/json

### get teacher by id
GET http://localhost:8001/api/teachers/2 HTTP/1.1
content-type: application/json


### remove teacher by id
DELETE http://localhost:8001/api/teachers/1 HTTP/1.1
content-type: application/json



############ Ticket states #################
### Create a ticket state
POST http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json

{
    "state_name": "Awaiting Review"
}

### Create a ticket state
POST http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json

{
    "state_name": "Awaiting Confirmation"
}


### Create a ticket state
POST http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json

{
    "state_name": "Confirmed"
}



### get all ticket state
GET http://localhost:8001/api/ticket_states/ HTTP/1.1
content-type: application/json

### get ticket state by id
GET http://localhost:8001/api/ticket_states/1 HTTP/1.1
content-type: application/json


### remove ticket state by id
DELETE http://localhost:8001/api/ticket_states/1 HTTP/1.1
content-type: application/json


### Remove some ticket
DELETE http://localhost:8001/api/ticket/3 HTTP/1.1
content-type: application/json